### ISSUE TITLE
KVM_SET_LAPIC

### ISSUE THREAD

**Issue by brendank310** [Bareflank/MicroV#103]
Add ioctl KVM_SET_LAPIC to the shim, along with integration tests.

**Comment by fwsGonzo** [comment]
Just a FYI - it is possible to use the LAPIC outside of KVM without ever mapping it in to the VM address space. I'm using it as execution timeout that way. It's costly to copy 1K every time you enter, but it's only 2 micros, if you can afford that.

If this is full system emulation then I guess it would be less attractive.
