### ISSUE TITLE
are there any Signed drivers for production?

### ISSUE THREAD

**Issue by danyhm** [Bareflank/MicroV#22]
Hello,

I've a windows binary that checks the result of CPUID instructions to perform some actions. since CPUID is a memonic and hooking it is not possible , the only option is to use a hypervisor to trap the instruction and alter the results.

now the problem is that I can't use testmode and can't disable UEFI.

I was wondering are there any signed driver that solves this problem? if no , is there any way to get hold of a software that has the kernel driver signed which only perform some basic tasks , and a SDK is provided to interact and control the driver? does this make sense?

for example VMware drivers are signed and using the software I can tamper the CPUID a little with some .vmx modifications but I can't alter the results. is there something similar for micro hypervisors which allows that kind of access and has the drivers signed?

**Comment by rianquinn** [comment]
Currently we do not. Based on your description, you would likely only need the Bareflank Hypervisor, not MicroV. But either way, we don't provided signed drivers. The Bareflank Hypervisor is an SDK for doing exactly what you are talking about, but you have to sign the drivers yourself. MicroV is a type 1 hypervisor, so once it is complete, it will run from UEFI. We likely will have a signed UEFI binary, but it would be for MicroV, not a modded version.
